//! `vibetty setup` —— TUI 配置 MQTT 传输,写入 `~/.vibetty/config.toml` 的 `[mqtt]` 段。
//!
//! 上下选择字段,Enter 进入编辑,字符直接输入(←/→ 移光标),`s` 手动保存。
//! `q`/Esc 退出时:若有未保存的改动 → 弹确认框(显示将写入的配置路径),
//! Y 保存并退出 / N 或 Esc 放弃改动退出;无改动则直接退出。

use crossterm::{
    event::{self, KeyCode, KeyEventKind},
    execute,
    terminal::{EnterAlternateScreen, LeaveAlternateScreen, disable_raw_mode, enable_raw_mode},
};
use ratatui::{
    Frame, Terminal,
    backend::CrosstermBackend,
    layout::{Alignment, Constraint, Direction, Layout},
    style::{Color, Modifier, Style},
    text::Line,
    widgets::{Block, Borders, List, ListItem, ListState, Paragraph},
};
use std::io::Stdout;

use crate::config::MqttConfig;

type Term = Terminal<CrosstermBackend<Stdout>>;

fn config_path(override_path: Option<&std::path::Path>) -> Option<std::path::PathBuf> {
    match override_path {
        Some(p) => Some(p.to_path_buf()),
        None => dirs::home_dir().map(|h| h.join(".vibetty").join("config.toml")),
    }
}

/// 读取现有 `[mqtt]` 段,用于预填表单。config 文件不存在时先生成一个带注释骨架
/// (含 `[mqtt]` 段),让首次运行的用户有东西可看可改,再从生成的文件里读回默认值。
fn load_mqtt(override_path: Option<&std::path::Path>) -> Option<MqttConfig> {
    let path = config_path(override_path)?;
    if !path.exists() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        // 已存在就不动(下面的 read_to_string 会正常读);只在缺文件时落一份骨架。
        std::fs::write(&path, default_config_toml()).ok();
        log::info!(
            "[setup] no config file at {}; generated a starter one",
            path.display()
        );
    }
    let content = std::fs::read_to_string(&path).ok()?;
    #[derive(serde::Deserialize)]
    struct Section {
        #[serde(default)]
        mqtt: Option<MqttConfig>,
    }
    toml::from_str::<Section>(&content).ok()?.mqtt
}

/// 新用户的初始 config.toml 骨架:`[mqtt]` 全字段 + 注释说明(broker 指向 localhost
/// 即自动用内置 broker)。
fn default_config_toml() -> String {
    r#"# vibetty configuration (generated by `vibetty setup`)
# Edit with `vibetty setup`, or by hand.

[mqtt]
# Set false to keep the config but disable MQTT entirely.
enable = true
# Broker URL. If the host is localhost / 127.0.0.1, vibetty automatically starts
# its built-in broker on the port in this URL (default 1883) — nothing else to run.
broker = "mqtt://127.0.0.1:1883"
# QoS: 0 / 1 / 2
qos = 1
keep_alive_secs = 30
"#
    .to_string()
}

/// 把 `[mqtt]` 段写回 config.toml(默认 `~/.vibetty/config.toml`),保留文件中已有的其它段。
pub(crate) fn save_mqtt(
    mqtt: &MqttConfig,
    override_path: Option<&std::path::Path>,
) -> anyhow::Result<()> {
    let path =
        config_path(override_path).ok_or_else(|| anyhow::anyhow!("Cannot find home directory"))?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut table: toml::Table = std::fs::read_to_string(&path)
        .ok()
        .and_then(|s| toml::from_str(&s).ok())
        .unwrap_or_default();
    table.insert("mqtt".to_string(), toml::Value::try_from(mqtt)?);
    std::fs::write(&path, toml::to_string_pretty(&table)?)?;
    Ok(())
}

struct Field {
    label: &'static str,
    value: String,
    /// 文本/数值字段的光标位置(字节偏移,指向待插入点);bool 字段不用。
    cursor: usize,
    hint: &'static str,
}

fn fields_from(existing: Option<&MqttConfig>) -> Vec<Field> {
    let e = existing.cloned();
    // 字段构造助手:cursor 初始放到末尾(追加输入的最自然位置)。
    let mk = |label: &'static str, value: String, hint: &'static str| {
        let cursor = value.len();
        Field {
            label,
            value,
            cursor,
            hint,
        }
    };
    vec![
        mk(
            "enable",
            e.as_ref()
                .map(|c| c.enable.to_string())
                .unwrap_or_else(|| "true".into()),
            "[Space] toggle true / false",
        ),
        mk(
            "broker",
            e.as_ref().map(|c| c.broker.clone()).unwrap_or_default(),
            "mqtt(s)://[user:pass@]host:port  (localhost host = built-in broker, URL port used)",
        ),
        mk(
            "qos",
            e.as_ref()
                .map(|c| c.qos.to_string())
                .unwrap_or_else(|| "1".into()),
            "0 / 1 / 2, default 1",
        ),
        mk(
            "keep_alive_secs",
            e.as_ref()
                .map(|c| c.keep_alive_secs.to_string())
                .unwrap_or_else(|| "30".into()),
            "Default 30",
        ),
    ]
}

fn field<'a>(fields: &'a [Field], label: &str) -> &'a Field {
    fields
        .iter()
        .find(|f| f.label == label)
        .expect("MQTT field always present")
}

/// 由表单字段构建 `MqttConfig`。
/// broker URL 必填(enable=true 时);builtin_* 三项不在表单里——内置 broker 由
/// broker 是否指向回环地址自动判定,w 仅作透传保留配置里已有的值(默认 1883/0/false)。
fn mqtt_from_fields(fields: &[Field], prev: Option<&MqttConfig>) -> anyhow::Result<MqttConfig> {
    let enable = match field(fields, "enable").value.trim() {
        "" | "true" | "1" => true,
        "false" | "0" => false,
        s => anyhow::bail!("invalid enable: {s} (true / false)"),
    };
    let broker = field(fields, "broker").value.trim().to_string();
    if enable && broker.is_empty() {
        anyhow::bail!("broker URL is required when enable=true");
    }
    let qos = parse_or(field(fields, "qos"), 1)?;
    let keep_alive_secs = parse_or(field(fields, "keep_alive_secs"), 30)?;
    Ok(MqttConfig {
        enable,
        broker,
        // 以下三项不在表单中:透传已有配置里的值,不丢用户之前的设置。
        builtin_broker: prev.is_some_and(|c| c.builtin_broker),
        builtin_port: prev.map(|c| c.builtin_port).unwrap_or_default(),
        builtin_ws_port: prev.map(|c| c.builtin_ws_port).unwrap_or_default(),
        qos,
        keep_alive_secs,
    })
}

fn parse_or<T: std::str::FromStr>(fld: &Field, default: T) -> anyhow::Result<T> {
    let raw = fld.value.trim();
    if raw.is_empty() {
        return Ok(default);
    }
    raw.parse::<T>()
        .map_err(|_| anyhow::anyhow!("cannot parse {}: {raw}", fld.label))
}

#[derive(Clone, Copy, PartialEq)]
enum Mode {
    Select,
    Edit,
    /// 退出前确认:有未保存改动时弹出,Y 保存退出 / N 放弃退出 / Esc 回表单。
    ConfirmQuit,
}

pub fn run_setup(config: Option<std::path::PathBuf>) -> anyhow::Result<()> {
    let override_path = config.as_deref();
    let existing = load_mqtt(override_path);
    let mut fields = fields_from(existing.as_ref());
    // 初始(磁盘上)的 [mqtt] 段;用于判断「是否有未保存改动」。
    let initial = existing.clone();
    let mut state = ListState::default();
    state.select(Some(0));
    let mut mode = Mode::Select;
    let mut status: Option<String> = None;

    enable_raw_mode()?;
    let mut stdout = std::io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    let result = setup_loop(
        &mut terminal,
        &mut fields,
        existing.as_ref(),
        &initial,
        &mut state,
        &mut mode,
        &mut status,
        override_path,
    );

    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    terminal.show_cursor()?;

    result
}

/// 当前表单是否和初始(加载时)的值不同。
fn dirty(fields: &[Field], prev: Option<&MqttConfig>, initial: &Option<MqttConfig>) -> bool {
    match mqtt_from_fields(fields, prev) {
        // 磁盘上原本没有 [mqtt](initial=None)而表单是默认值时,Some(default) == None
        // 不成立,会误报 dirty;把「磁盘无段且表单等于全默认」视作未改动太绕,
        // 这里只在「能解析出 config 且与初始不同」时报 dirty,解析失败一律视为有改动。
        Ok(now) => initial.as_ref().is_some_and(|i| now != *i),
        Err(_) => true, // 表单填出非法值也算有改动
    }
}

#[allow(clippy::too_many_arguments)]
fn setup_loop(
    terminal: &mut Term,
    fields: &mut [Field],
    prev: Option<&MqttConfig>,
    initial: &Option<MqttConfig>,
    state: &mut ListState,
    mode: &mut Mode,
    status: &mut Option<String>,
    override_path: Option<&std::path::Path>,
) -> anyhow::Result<()> {
    loop {
        terminal.draw(|f| draw(f, fields, state, *mode, status.as_deref()))?;

        if !event::poll(std::time::Duration::from_millis(100))? {
            continue;
        }
        let event::Event::Key(key) = event::read()? else {
            continue;
        };
        if key.kind != KeyEventKind::Press {
            continue;
        }

        // 确认框:y/Y/Enter=保存并退出;n/N=放弃退出;Esc=回到表单;其余忽略。
        if *mode == Mode::ConfirmQuit {
            match key.code {
                KeyCode::Char('y') | KeyCode::Char('Y') | KeyCode::Enter => {
                    return save_and_finish(fields, prev, override_path, status);
                }
                KeyCode::Char('n') | KeyCode::Char('N') | KeyCode::Esc => return Ok(()),
                _ => {}
            }
        }

        // 保存/出错后,任意键退出。
        if status.is_some() {
            return Ok(());
        }

        match mode {
            // ConfirmQuit 在上面的专属分支处理过,这里不会有。
            Mode::ConfirmQuit => unreachable!("handled above"),
            Mode::Select => match key.code {
                KeyCode::Char('q') | KeyCode::Esc => {
                    if dirty(fields, prev, initial) {
                        *mode = Mode::ConfirmQuit;
                    } else {
                        return Ok(());
                    }
                }
                KeyCode::Char('s') => match mqtt_from_fields(fields, prev) {
                    Ok(cfg) => match save_mqtt(&cfg, override_path) {
                        Ok(()) => {
                            let p = config_path(override_path)
                                .map(|p| p.display().to_string())
                                .unwrap_or_default();
                            *status = Some(format!("Saved to {p}. Press any key to exit."));
                        }
                        Err(e) => *status = Some(format!("Save failed: {e}")),
                    },
                    Err(e) => *status = Some(format!("Invalid input: {e}")),
                },
                KeyCode::Up => state.select_previous(),
                KeyCode::Down => state.select_next(),
                KeyCode::Enter => *mode = Mode::Edit,
                _ => {}
            },
            Mode::Edit => {
                let Some(i) = state.selected() else {
                    *mode = Mode::Select;
                    continue;
                };
                let is_bool = matches!(fields[i].label, "enable" | "builtin_broker");
                let f = &mut fields[i];
                match key.code {
                    KeyCode::Esc | KeyCode::Enter => *mode = Mode::Select,
                    // bool 字段:按键切换,不逐字输入(无光标移动)
                    KeyCode::Char(' ') if is_bool => {
                        f.value = if f.value.trim() == "true" {
                            "false"
                        } else {
                            "true"
                        }
                        .to_string();
                    }
                    KeyCode::Char('t') | KeyCode::Char('T') if is_bool => {
                        f.value = "true".to_string();
                    }
                    KeyCode::Char('f') | KeyCode::Char('F') if is_bool => {
                        f.value = "false".to_string();
                    }
                    // 文本/数值字段:←/→ 移光标,Home/End 跳首尾
                    KeyCode::Left if !is_bool => f.cursor = f.cursor.saturating_sub(1),
                    KeyCode::Right if !is_bool => f.cursor = (f.cursor + 1).min(f.value.len()),
                    KeyCode::Home if !is_bool => f.cursor = 0,
                    KeyCode::End if !is_bool => f.cursor = f.value.len(),
                    // Backspace 删光标前一个字符;Delete 删光标所在字符
                    KeyCode::Backspace if !is_bool => {
                        if f.cursor > 0 {
                            f.cursor -= 1;
                            f.value.remove(f.cursor);
                        }
                    }
                    KeyCode::Delete if !is_bool => {
                        if f.cursor < f.value.len() {
                            f.value.remove(f.cursor);
                        }
                    }
                    KeyCode::Char(c) if !is_bool => {
                        f.value.insert(f.cursor, c);
                        f.cursor += 1;
                    }
                    _ => {}
                }
            }
        }
    }
}

/// 保存表单到 config;成功时置 saved 状态(用户随后任意键退出)。
fn save_and_finish(
    fields: &[Field],
    prev: Option<&MqttConfig>,
    override_path: Option<&std::path::Path>,
    status: &mut Option<String>,
) -> anyhow::Result<()> {
    match mqtt_from_fields(fields, prev) {
        Ok(cfg) => match save_mqtt(&cfg, override_path) {
            Ok(()) => {
                let p = config_path(override_path)
                    .map(|p| p.display().to_string())
                    .unwrap_or_default();
                *status = Some(format!("Saved to {p}. Press any key to exit."));
                Ok(())
            }
            Err(e) => {
                *status = Some(format!("Save failed: {e} — press any key to exit."));
                Ok(())
            }
        },
        Err(e) => {
            *status = Some(format!("Invalid input: {e} — fix and try again."));
            Ok(())
        }
    }
}

/// 退出确认弹窗(居中,显示将写入的配置路径)。
fn draw_confirm_popup(f: &mut Frame) {
    let path = dirs::home_dir()
        .map(|h| h.join(".vibetty").join("config.toml"))
        .map(|p| p.display().to_string())
        .unwrap_or_default();
    let area = centered_rect(f.area(), 62, 7);
    f.render_widget(ratatui::widgets::Clear, area);
    let block = Block::default()
        .borders(Borders::ALL)
        .title(" Unsaved changes ")
        .style(Style::default().fg(Color::Yellow));
    let text = vec![
        Line::from("You have unsaved changes."),
        Line::from(String::new()),
        Line::from(format!("Save to: {path}?")),
        Line::from(String::new()),
        Line::from("Y save & exit   N discard & exit   Esc back"),
    ];
    f.render_widget(Paragraph::new(text).block(block), area);
}

/// 以 (cols, rows) 为中心取一块矩形(越界自动收紧)。
fn centered_rect(area: ratatui::layout::Rect, cols: u16, rows: u16) -> ratatui::layout::Rect {
    use ratatui::layout::Rect;
    let w = cols.min(area.width);
    let h = rows.min(area.height);
    Rect {
        x: area.x + (area.width.saturating_sub(w)) / 2,
        y: area.y + (area.height.saturating_sub(h)) / 2,
        width: w,
        height: h,
    }
}

fn draw(f: &mut Frame, fields: &[Field], state: &mut ListState, mode: Mode, status: Option<&str>) {
    let chunks = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Length(3),
            Constraint::Min(1),
            Constraint::Length(3),
        ])
        .split(f.area());

    let title = Paragraph::new("Vibetty — MQTT setup  (~/.vibetty/config.toml)")
        .alignment(Alignment::Center)
        .block(Block::default().borders(Borders::ALL));
    f.render_widget(title, chunks[0]);

    let items: Vec<ListItem<'_>> = fields
        .iter()
        .enumerate()
        .map(|(i, fld)| {
            let sel = state.selected() == Some(i);
            let editing = sel && mode == Mode::Edit;
            let is_bool = matches!(fld.label, "enable" | "builtin_broker");
            let val = if editing && is_bool {
                format!("[{}]", fld.value)
            } else if editing {
                // 把光标块 ▌ 插到 cursor 位置,直观显示插入点。
                let mut s = fld.value.clone();
                s.insert(fld.cursor.min(s.len()), '▌');
                s
            } else if fld.value.is_empty() {
                "(empty)".to_string()
            } else {
                fld.value.clone()
            };
            ListItem::new(Line::from(format!(
                " {:<15}: {:<26}  {}",
                fld.label, val, fld.hint
            )))
        })
        .collect();
    let list = List::new(items)
        .block(Block::default().borders(Borders::ALL).title("MQTT fields"))
        .highlight_style(
            Style::default()
                .fg(Color::Yellow)
                .add_modifier(Modifier::BOLD),
        )
        .highlight_symbol("▶");
    f.render_stateful_widget(list, chunks[1], state);

    let footer = match status {
        Some(s) => s.to_string(),
        None => match mode {
            Mode::Select => " ↑/↓ select  ·  Enter edit  ·  q/Esc quit".to_string(),
            Mode::Edit => {
                " type to edit  ·  ←/→ Home/End move  ·  Del  ·  [Space] bool  ·  Enter/Esc done"
                    .to_string()
            }
            Mode::ConfirmQuit => String::new(),
        },
    };
    f.render_widget(
        Paragraph::new(footer).alignment(Alignment::Center),
        chunks[2],
    );

    // 退出确认弹窗:最后画,盖在表单上面。
    if mode == Mode::ConfirmQuit {
        draw_confirm_popup(f);
    }
}
